export const baseContext = {
  service: "meals",
  secondary: "none",
  scope: "day",
  date: "2026-09-21",
  meal: "lunch",
  metric: "all",
  leaveView: "apply",
  leaveKind: "full",
};
const meal = (kind, scope = "day") => ({ ...baseContext, meal: kind, scope });
const leave = (view) => ({ ...baseContext, service: "leave", leaveView: view });
const weather = (metric) => ({ ...baseContext, service: "weather", metric });
export const cases = [
  ["점심메뉴", null, { service: "meals", meal: "lunch" }, "MealSingleCard"],
  [
    "오늘 저녁 메뉴",
    null,
    { service: "meals", meal: "dinner" },
    "MealSingleCard",
  ],
  [
    "저녁은?",
    meal("lunch"),
    { service: "meals", meal: "dinner" },
    "MealSingleCard",
  ],
  [
    "점심 말고 저녁 메뉴",
    meal("lunch"),
    { service: "meals", meal: "dinner" },
    "MealSingleCard",
  ],
  [
    "저녁 말고 점심 보여줘",
    meal("dinner"),
    { service: "meals", meal: "lunch" },
    "MealSingleCard",
  ],
  [
    "내일은?",
    meal("dinner"),
    { service: "meals", meal: "dinner" },
    "MealSingleCard",
  ],
  [
    "아침 메뉴 보여줘",
    null,
    { service: "meals", meal: "breakfast" },
    "MealSingleCard",
  ],
  [
    "석식 뭐 나와?",
    null,
    { service: "meals", meal: "dinner" },
    "MealSingleCard",
  ],
  [
    "전체메뉴",
    meal("dinner"),
    { service: "meals", meal: "all", scope: "day" },
    "MealDayCard",
  ],
  [
    "이번 주 저녁 식단",
    null,
    { service: "meals", meal: "dinner", scope: "week" },
    "MealWeekCard",
  ],
  [
    "잔여휴가일수",
    null,
    { service: "leave", leaveView: "balance" },
    "LeaveBalanceCard",
  ],
  [
    "휴가신청",
    leave("balance"),
    { service: "leave", leaveView: "apply" },
    "LeaveApplicationCard",
  ],
  [
    "잔여휴가일수",
    leave("apply"),
    { service: "leave", leaveView: "balance" },
    "LeaveBalanceCard",
  ],
  [
    "신청 말고 며칠 남았는지",
    leave("apply"),
    { service: "leave", leaveView: "balance" },
    "LeaveBalanceCard",
  ],
  [
    "잔여일수 말고 신청할래",
    leave("balance"),
    { service: "leave", leaveView: "apply" },
    "LeaveApplicationCard",
  ],
  [
    "내 연차 얼마나 남았어?",
    null,
    { service: "leave", leaveView: "balance" },
    "LeaveBalanceCard",
  ],
  [
    "신청 내역 보여줘",
    leave("apply"),
    { service: "leave", leaveView: "status" },
    "LeaveHistoryCard",
  ],
  [
    "휴가 신청한 거 취소하고 싶어",
    leave("balance"),
    { service: "leave", leaveView: "status" },
    "LeaveHistoryCard",
  ],
  [
    "오후 반차 신청할게",
    leave("balance"),
    { service: "leave", leaveView: "apply", leaveKind: "pm" },
    "LeaveApplicationCard",
  ],
  ["오늘 일정", null, { service: "schedule", scope: "day" }, "ScheduleDayCard"],
  [
    "이번 주 전체 일정",
    null,
    { service: "schedule", scope: "week" },
    "ScheduleWeekCard",
  ],
  [
    "오늘 날씨",
    null,
    { service: "weather", metric: "all" },
    "WeatherOverviewCard",
  ],
  [
    "오늘 온도",
    null,
    { service: "weather", metric: "temperature" },
    "WeatherMetricCard",
  ],
  [
    "오늘 습도",
    weather("temperature"),
    { service: "weather", metric: "humidity" },
    "WeatherMetricCard",
  ],
  [
    "습도 말고 온도",
    weather("humidity"),
    { service: "weather", metric: "temperature" },
    "WeatherMetricCard",
  ],
  [
    "내일은?",
    weather("humidity"),
    { service: "weather", metric: "humidity" },
    "WeatherMetricCard",
  ],
  [
    "이번 주 날씨",
    null,
    { service: "weather", scope: "week", metric: "all" },
    "WeatherWeekCard",
  ],
  ["내일 회의실 예약", null, { service: "rooms" }, "RoomBookingCard"],
  ["사내 공지 보여줘", null, { service: "notices" }, "NoticeListCard"],
  [
    "자바스크립트 Promise 설명해줘",
    leave("apply"),
    { service: "llm" },
    "LLMHandoffCard",
  ],
];
